version: "3.8"

services:
  backend:
    build: ./backend
    container_name: pneumonia-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: pneumonia-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
